# Site settings
title: "KJ Bondes"
author: "KJ Bondes"
email: kuanju.bondes@posteo.de
description:
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kjbondes.github.io"

github_username:  "kjbondes"
linkedin: "https://www.linkedin.com/in/kuanjupan/"
xing: "https://www.xing.com/profile/KuanJu_Bondes/"

exclude: ['README', 'Gemfile.lock', '.jekyll-cache', 'Rakefile']  

# Build settings
markdown: kramdown

sass:
  sass_dir: _sass
  style: compressed

# Plugins
plugins:
  - jekyll-multiple-languages-plugin

# jekyll-multiple-languages-plugin settings:
languages: ["de", "en"]
exclude_from_localizations: ["js", "img", "css", "fonts", "download"]
