# put here any directive needed only when deploying
# a special deploy_dir variable specifies the deployment location using rsync

baseurl: https://kjbondes.github.io
deploy_dir: git@github.com:/kjbondes/kjbondes.github.io.git